export {
  CreateTaskDocument as CREATE_TASK_MUTATION,
  DeleteTaskDocument as DELETE_TASK_MUTATION,
  HouseholdShellDocument as HOUSEHOLD_SHELL_QUERY,
  MoveTaskDocument as MOVE_TASK_MUTATION,
  TasksBoardDocument as TASKS_BOARD_QUERY,
  UpdateTaskDocument as UPDATE_TASK_MUTATION,
  MealPlanDocument as MEAL_PLAN_QUERY,
  CreateRecipeDocument as CREATE_RECIPE_MUTATION,
  UpdateRecipeDocument as UPDATE_RECIPE_MUTATION,
  DeleteRecipeDocument as DELETE_RECIPE_MUTATION,
  CreateRecipeFolderDocument as CREATE_RECIPE_FOLDER_MUTATION,
  MoveRecipeToFolderDocument as MOVE_RECIPE_TO_FOLDER_MUTATION,
  AssignMealPlanSlotDocument as ASSIGN_MEAL_PLAN_SLOT_MUTATION,
  ClearMealPlanSlotDocument as CLEAR_MEAL_PLAN_SLOT_MUTATION,
  AddGroceryItemDocument as ADD_GROCERY_ITEM_MUTATION,
  UpdateGroceryItemDocument as UPDATE_GROCERY_ITEM_MUTATION,
  DeleteGroceryItemDocument as DELETE_GROCERY_ITEM_MUTATION,
  RemoveBoughtGroceryItemsDocument as REMOVE_BOUGHT_GROCERY_ITEMS_MUTATION,
} from "./generated/graphql";

export type {
  CreateTaskMutation,
  CreateTaskMutationVariables,
  DeleteTaskMutation,
  DeleteTaskMutationVariables,
  HouseholdShellQuery,
  HouseholdShellQueryVariables,
  MoveTaskMutation,
  MoveTaskMutationVariables,
  TaskPriority,
  TasksBoardQuery,
  TasksBoardQueryVariables,
  TaskStatus,
  TaskView,
  UpdateTaskMutation,
  UpdateTaskMutationVariables,
  MealPlanQuery,
  MealPlanQueryVariables,
  MealSlot,
  WeekDay,
  CreateRecipeMutation,
  CreateRecipeMutationVariables,
  UpdateRecipeMutation,
  UpdateRecipeMutationVariables,
  DeleteRecipeMutation,
  DeleteRecipeMutationVariables,
  CreateRecipeFolderMutation,
  CreateRecipeFolderMutationVariables,
  MoveRecipeToFolderMutation,
  MoveRecipeToFolderMutationVariables,
  RecipeFolderColor,
  CreateRecipeFolderInput,
  AssignMealPlanSlotMutation,
  AssignMealPlanSlotMutationVariables,
  ClearMealPlanSlotMutation,
  ClearMealPlanSlotMutationVariables,
  AddGroceryItemMutation,
  AddGroceryItemMutationVariables,
  UpdateGroceryItemMutation,
  UpdateGroceryItemMutationVariables,
  DeleteGroceryItemMutation,
  DeleteGroceryItemMutationVariables,
  RemoveBoughtGroceryItemsMutation,
  RemoveBoughtGroceryItemsMutationVariables,
  RecipeIngredientInput,
  CreateRecipeInput,
  UpdateRecipeInput,
  AddGroceryItemInput,
  UpdateGroceryItemInput,
} from "./generated/graphql";
