import { BUDGET_LINE_ALLOCATIONS_QUERY, BUDGET_MONTH_QUERY, BANK_CONNECTIONS_QUERY } from "@/graphql";

export const BUDGET_PAGE_REFETCH = [BUDGET_MONTH_QUERY, BANK_CONNECTIONS_QUERY] as const;
export const BUDGET_LINE_ALLOCATIONS_REFETCH = [
  BUDGET_LINE_ALLOCATIONS_QUERY,
  BUDGET_MONTH_QUERY,
  BANK_CONNECTIONS_QUERY,
] as const;
export const BANK_CONNECTIONS_REFETCH = [BANK_CONNECTIONS_QUERY, BUDGET_MONTH_QUERY] as const;
