import { BUDGET_LINE_ALLOCATIONS_QUERY, BUDGET_MONTH_QUERY } from "@/graphql";

export const BUDGET_PAGE_REFETCH = [BUDGET_MONTH_QUERY] as const;
export const BUDGET_LINE_ALLOCATIONS_REFETCH = [BUDGET_LINE_ALLOCATIONS_QUERY, BUDGET_MONTH_QUERY] as const;
